inveroryManagerApp/Controllers/CustomersController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using inveroryManagerApp.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace inveroryManagerApp.Controllers;

public partial class CustomersController : Controller
{
    public IActionResult ListCustomers()
    {
        DatabaseConnection db = new DatabaseConnection();
        ViewBag.model = db.GetListOfCustomers();
        return View();
    }

    [HttpGet]
    public IActionResult AddCustomer()
    {
        return View();
    }

    [HttpPost]
    public IActionResult AddCustomer(CustomerModel customer)
    {
        DatabaseConnection db = new DatabaseConnection();
        db.AddCustomer(customer);
        return Redirect("ListCustomers");
    }

    [HttpGet]
    public IActionResult EditCustomer(int customerid)
    {
        DatabaseConnection db = new DatabaseConnection();
        CustomerModel customerData = db.GetCustomerByCustomerId(customerid);
        return View(customerData);
    }

    [HttpPost]
    public IActionResult EditCustomer(CustomerModel customer)
    {
        DatabaseConnection db = new DatabaseConnection();
        db.EditCustomer(customer);
        return Redirect("ListCustomers");
    }

    [HttpGet]
    public IActionResult BuyItems()
    {
        DatabaseConnection db = new DatabaseConnection();

        List<CustomerModel> customerList = db.GetListOfCustomers();
        List<SelectListItem> customerItems = new List<SelectListItem>();
        customerItems.Add(new SelectListItem { Text = "--Select Customer--", Value = "0" });
        foreach (CustomerModel customerItem in customerList)
        {
            customerItems.Add(new SelectListItem { Text = customerItem.CustomerName, Value = customerItem.CustomerId.ToString() });
        }
        ViewBag.listCustomer = customerItems;

        List<StaffModel> staffList = db.GetListOfStaffs();
        List<SelectListItem> staffItems = new List<SelectListItem>();
        staffItems.Add(new SelectListItem { Text = "--Select Staff--", Value = "0" });
        foreach (StaffModel staffItem in staffList)
        {
            staffItems.Add(new SelectListItem { Text = staffItem.StaffName, Value = staffItem.StaffId.ToString() });
        }
        ViewBag.listStaff = staffItems;

        List<ItemModel> itemList = db.GetListOfItems();
        List<SelectListItem> itemItems = new List<SelectListItem>();
        //itemItems.Add(new SelectListItem { Text = "--Select Item--", Value = "0" });
        foreach (ItemModel itemItem in itemList)
        {
            itemItems.Add(new SelectListItem { Text = itemItem.ItemName + " (" + itemItem.SellPrice + ")", Value = itemItem.ItemId.ToString() });
        }
        ViewBag.listItem = itemItems;

        BuyItemModel objStudentModel = new BuyItemModel();
        objStudentModel.listItem = itemItems;

        return View();
    }

    [HttpPost]
    public IActionResult BuyItems(BuyItemModel buyItem)
    {
        DatabaseConnection db = new DatabaseConnection();
        db.AddTransaction(buyItem);
        return Redirect("ListTransactions");
    }

    public IActionResult ListTransactions()
    {
        DatabaseConnection db = new DatabaseConnection();
        ViewBag.model = db.GetTransactions();
        return View();
    }

    public IActionResult ViewTransactions(int transactionid)
    {
        DatabaseConnection db = new DatabaseConnection();
        ViewBag.model = db.GetTransactionDetailsByTransactionId(transactionid);
        ViewBag.transaction = db.GetTransactionByTransactionId(transactionid);
        return View();
    }
}

inveroryManagerApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using inveroryManagerApp.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace inveroryManagerApp.Controllers;

public partial class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Orders()
    {
        return View();
    }

    public IActionResult Items()
    {
        return View();
    }

    public IActionResult Customers()
    {
        return View();
    }

    public IActionResult Staffs()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

inveroryManagerApp/Controllers/ItemsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using inveroryManagerApp.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace inveroryManagerApp.Controllers;

public partial class ItemsController : Controller
{

    public IActionResult ListItems()
    {
        DatabaseConnection db = new DatabaseConnection();
        List<ItemModel> listOfItems = db.GetListOfItems();
        ViewBag.Categories = db.GetItemCategoryModels(); 
        ViewBag.model = listOfItems;
        return View();
    }

    public delegate List<ItemModel> FilterDelegate(List<ItemModel> im);

    [HttpPost]
    public IActionResult ListItems(string filters)
    {
        DatabaseConnection db = new DatabaseConnection();
        FilterClass filterClass = new FilterClass();
        List<ItemModel> listOfItems = db.GetListOfItems();
        ViewBag.Categories = db.GetItemCategoryModels();

        if(filters == "Price: High to Low")
        {
            ViewBag.model = filterClass.PerformFilter(listOfItems, filterClass.PriceHighLow);
        }
        else if (filters == "Price: Low to High")
        {
            ViewBag.model = filterClass.PerformFilter(listOfItems, filterClass.PriceLowHigh);
        }
        else
        {
            ViewBag.model = listOfItems;
        }

        return View();
    }

    public class FilterClass
    {
        public FilterClass() { }

        public List<ItemModel> PerformFilter(List<ItemModel> items, FilterDelegate filter)
        {
            return filter.Invoke(items);
        }

        public List<ItemModel> PriceHighLow(List<ItemModel> list)
        {
            return list.OrderByDescending(x => x.SellPrice).ToList();
        }

        public List<ItemModel> PriceLowHigh(List<ItemModel> list)
        {
            return list.OrderBy(x => x.SellPrice).ToList();
        }
    }

    [HttpGet]
    public IActionResult AddCompany()
    {
        return View();
    }

    [HttpPost]
    public IActionResult AddCompany(CompanyModel company)
    {
        DatabaseConnection db = new DatabaseConnection();
        db.AddCompany(company);
        return Redirect("AddItem");
    }

    [HttpGet]
    public IActionResult AddSupplier()
    {
        return View();
    }

    [HttpPost]
    public IActionResult AddSupplier(SupplierModel supplier)
    {
        DatabaseConnection db = new DatabaseConnection();
        db.AddSupplier(supplier);
        return Redirect("AddItem");
    }

    [HttpGet]
    public IActionResult AddItemCategory()
    {
        return View();
    }

    [HttpPost]
    public IActionResult AddItemCategory(ItemCategoryModel itemCategory)
    {
        DatabaseConnection db = new DatabaseConnection();
        db.AddItemCategory(itemCategory);
        return Redirect("AddItem");
    }

    [HttpGet]
    public IActionResult AddItem()
    {
        DatabaseConnection db = new DatabaseConnection();

        List<CompanyModel> companyList = db.GetListOfCompany();
        List<SelectListItem> companyItems = new List<SelectListItem>();
        companyItems.Add(new SelectListItem { Text = "--Select Company--", Value = "0" });
        foreach (CompanyModel companyItem in companyList)
        {
            companyItems.Add(new SelectListItem { Text = companyItem.CompanyName, Value = companyItem.CompanyId.ToString() });
        }
        ViewBag.listCompany = companyItems;

        List<SupplierModel> supplierList = db.GetListOfSupplier();
        List<SelectListItem> supplierItems = new List<SelectListItem>();
        supplierItems.Add(new SelectListItem { Text = "--Select Supplier--", Value = "0" });
        foreach (SupplierModel supplierItem in supplierList)
        {
            supplierItems.Add(new SelectListItem { Text = supplierItem.SupplierName, Value = supplierItem.SupplierId.ToString() });
        }
        ViewBag.listSupplier = supplierItems;

        List<ItemCategoryModel> itemCategoryList = db.GetItemCategoryModels();
        List<SelectListItem> itemCategoryItems = new List<SelectListItem>();
        itemCategoryItems.Add(new SelectListItem { Text = "--Select Item Category--", Value = "0" });
        foreach (ItemCategoryModel itemCategoryItem in itemCategoryList)
        {
            itemCategoryItems.Add(new SelectListItem { Text = itemCategoryItem.ItemCategoryName, Value = itemCategoryItem.ItemCategoryId.ToString() });
        }
        ViewBag.listItemCategory = itemCategoryItems;
        return View();
    }

    [HttpPost]
    public IActionResult AddItem(ItemModel item)
    {
        DatabaseConnection db = new DatabaseConnection();
        db.AddItem(item);
        return Redirect("ListItems");
    }

    [HttpGet]
    public IActionResult ViewItem(int itemid)
    {
        DatabaseConnection db = new DatabaseConnection();
        ViewBag.model = db.GetItemByItemId(itemid);
        return View();
    }

}

inveroryManagerApp/Controllers/OrderController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using inveroryManagerApp.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using inveroryManagerApp.Event;

namespace inveroryManagerApp.Controllers;

public partial class OrdersController : Controller
{
    private readonly OrderProcessor _orderProcessor;
    public OrdersController()
  {
        _orderProcessor = new OrderProcessor();
        var emailService = new EmailService();
        _orderProcessor.OrderProcessed += emailService.OnOrderProcessed;
    }

    public IActionResult ListOrders()
    {
        DatabaseConnection db = new DatabaseConnection();
        List<OrderModel> listOfOrders = db.GetOrders();
        ViewBag.model = listOfOrders;
        return View();
    }

    [HttpGet]
    public IActionResult AddOrder()
    {
        DatabaseConnection db = new DatabaseConnection();
        List<ItemModel> itemList = db.GetListOfItems();
        List<SelectListItem> itemItems = new List<SelectListItem>();
        itemItems.Add(new SelectListItem { Text = "--Select Item--", Value = "0" });
        foreach (ItemModel itemItem in itemList)
        {
            itemItems.Add(new SelectListItem { Text = itemItem.ItemName, Value = itemItem.ItemId.ToString() });
        }
        ViewBag.listItem = itemItems;
        return View();
    }

    [HttpPost]
    public IActionResult AddOrder(OrderModel order)
    {
        DatabaseConnection db = new DatabaseConnection();
        db.AddOrder(order);
        _orderProcessor.ProcessOrder(order);
        return Redirect("ListOrders");
    }

    [HttpGet]
    public IActionResult OrderStatus()
    {
        return View();
    }

    [HttpPost]
    public IActionResult DisplayOrderStatus(OrderModel order)
    {
        DatabaseConnection db = new DatabaseConnection();
        order = db.GetOrderById(order.OrderId);
        ViewBag.model = order;
        if (order == null)
            return NoContent();
        return View();
    }
}

inveroryManagerApp/Controllers/StaffController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using inveroryManagerApp.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace inveroryManagerApp.Controllers;

public partial class StaffController : Controller
{
    public IActionResult ListStaffs()
    {
        DatabaseConnection db = new DatabaseConnection();
        ViewBag.model = db.GetListOfStaffs();
        return View();
    }

    [HttpGet]
    public IActionResult AddStaff()
    {
        return View();
    }

    [HttpPost]
    public IActionResult AddStaff(StaffModel staff)
    {
        DatabaseConnection db = new DatabaseConnection();
        db.AddStaff(staff);
        return Redirect("ListStaffs");
    }
}

inveroryManagerApp/Views/Home/AddItem.cshtml
@model inveroryManagerApp.Models.ItemModel
@{
    ViewData["Title"] = "Add an Item";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .form-group{ margin: 5px; }
</style>

<div class="text-center">
    <h1 style="font-size: 4vw;">@ViewData["Title"]</h1>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group row">
            <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Company Name</label>
            <div class="col-sm-10">
                @Html.DropDownList("listCompany", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.listCompany, "", new { @class = "text-danger" })
                <a asp-action="AddCompany" asp-controller="home">
                    Add Company
                </a>
            </div>
        </div>

        <div class="form-group row">
            <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Supplier Name</label>
            <div class="col-sm-10">
                @Html.DropDownList("listSupplier", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.listSupplier, "", new { @class = "text-danger" })
                <a asp-action="AddSupplier" asp-controller="home">
                    Add Supplier
                </a>
            </div>
        </div>

        <div class="form-group row">
            <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Item Category Name</label>
            <div class="col-sm-10">
                @Html.DropDownList("listItemCategory", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.listItemCategory, "", new { @class = "text-danger" })
                <a asp-action="AddItemCategory" asp-controller="home">
                    Add Item Category
                </a>
            </div>
        </div>

        <div class="form-group row">
            <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Item Name</label>
            <div class="col-sm-10">
                @Html.EditorFor(model => model.ItemName, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                @Html.ValidationMessageFor(model => model.ItemName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Item Description</label>
            <div class="col-sm-10">
                @Html.EditorFor(model => model.ItemDescription, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                @Html.ValidationMessageFor(model => model.ItemDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Acquired Date</label>
            <div class="col-sm-10">
                @Html.EditorFor(model => model.AcquiredDate, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                @Html.ValidationMessageFor(model => model.AcquiredDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Cost Price</label>
            <div class="col-sm-10">
                @Html.EditorFor(model => model.CostPrice, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                @Html.ValidationMessageFor(model => model.CostPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Sell Price</label>
            <div class="col-sm-10">
                @Html.EditorFor(model => model.SellPrice, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                @Html.ValidationMessageFor(model => model.SellPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Quantity</label>
            <div class="col-sm-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Expiry Date</label>
            <div class="col-sm-10">
                @Html.EditorFor(model => model.ExpiryDate, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                @Html.ValidationMessageFor(model => model.ExpiryDate, "", new { @class = "text-danger" })
            </div>
        </div>




        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </div>
}

inveroryManagerApp/Views/Home/Customers.cshtml
@{
    ViewData["Title"] = "Customer Operations";
}
<div class="text-center">
    <h1 style="font-size: 4vw;">@ViewData["Title"]</h1>
</div>

<div class="position-absolute top-50 start-50 translate-middle ">
    <a asp-action="ListCustomers" asp-controller="Customers" class="btn btn-primary btn-lg"
       style="height: max-content">
        List Customers
    </a>
    <a asp-action="AddCustomer" asp-controller="Customers" class="btn btn-primary btn-lg"
       style="height: max-content">
        Add Customer
    </a>
    <a asp-action="BuyItems" asp-controller="Customers" class="btn btn-primary btn-lg"
       style="height: max-content">
        Buy Items
    </a>
    <a asp-action="ListTransactions" asp-controller="Customers" class="btn btn-primary btn-lg"
       style="height: max-content">
        List Transactions
    </a>
</div>

inveroryManagerApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Operation Select";
}

<div class="text-center">
    <h1 class="display-4" style="font-size: 6vw;">@ViewData["Title"]</h1>
</div>

<div class="position-absolute top-50 start-50 translate-middle ">
    <a asp-action="Orders" asp-controller="home" class="btn btn-primary btn-lg"
    style="height: max-content width: max-content; font-size: 2vw;">
        Orders
    </a>
    <a asp-action="Items" asp-controller="home" class="btn btn-primary btn-lg" 
    style="height: max-content; width: max-content; font-size: 2vw;">
        Items
    </a>
    <a asp-action="Customers" asp-controller="home" class="btn btn-primary btn-lg" 
    style="height: max-content; width: max-content; font-size: 2vw;">
        Customers
    </a>
    <a asp-action="Staffs" asp-controller="home" class="btn btn-primary btn-lg"
       style="height: max-content; width: max-content; font-size: 2vw;">
        Staffs
    </a>
</div>

inveroryManagerApp/Views/Home/Items.cshtml
@{
    ViewData["Title"] = "Items Operations";
}
<div class="text-center">
    <h1 style="font-size: 4vw;">@ViewData["Title"]</h1>
</div>

<div class="position-absolute top-50 start-50 translate-middle ">
    <a asp-action="ListItems" asp-controller="Items" class="btn btn-primary btn-lg"
    style="height: max-content width: max-content; font-size: 2vw;">
        List Items
    </a>
    <a asp-action="AddItem" asp-controller="Items" class="btn btn-primary btn-lg" 
    style="height: max-content; width: max-content; font-size: 2vw;">
        Add Item
    </a>
    @* <a asp-action="Index" asp-controller="Items" class="btn btn-primary btn-lg"
    style="height: max-content; width: max-content; font-size: 2vw;">
        Recall Item
    </a>
    <a asp-action="Index" asp-controller="home" class="btn btn-primary btn-lg" 
    style="height: max-content; width: max-content; font-size: 2vw;">
        Order Recieved
    </a> *@
</div>

inveroryManagerApp/Views/Home/ListItems.cshtml
@{
    ViewData["Title"] = "List Items";
}
<div class="text-center">
    <h1 style="font-size: 4vw;">@ViewData["Title"]</h1>
</div>

<form method="post" action="@Url.Action("ListItems", "Home")">
    @Html.DropDownList("filters", new SelectList(new List<string> { "Price: High to Low", "Price: Low to High"}), "Order By")
    <input type="submit" value="Submit" />
</form>

<div class="wrapper">
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Item Name</th>
                    <th scope="col">Company Name</th>
                    <th scope="col">Item Category Name</th>
                    <th scope="col">Price</th>
                </tr>
            </thead>
            @foreach (var item in ViewBag.model)
            {
                <tbody>
                    <tr>
                        <td>@item.ItemName</td>
                        <td>@item.Company.CompanyName</td>
                        <td>@item.ItemCategory.ItemCategoryName</td>
                        <td>@item.SellPrice</td>
                    </tr>
                </tbody>
            }
        </table>
    </div>
</div>

inveroryManagerApp/Views/Home/Orders.cshtml
@{
    ViewData["Title"] = "Orders Operations";
}
<div class="text-center">
    <h1 style="font-size: 4vw;">@ViewData["Title"]</h1>
</div>

<div class="position-absolute top-50 start-50 translate-middle ">
    <a asp-action="ListOrders" asp-controller="Orders" class="btn btn-primary btn-lg"
    style="height: max-content width: max-content; font-size: 2vw;">
        List Orders
    </a>
    <a asp-action="AddOrder" asp-controller="Orders" class="btn btn-primary btn-lg" 
    style="height: max-content; width: max-content; font-size: 2vw;">
        New Order
    </a>
    <a asp-action="OrderStatus" asp-controller="Orders" class="btn btn-primary btn-lg" 
    style="height: max-content; width: max-content; font-size: 2vw;">
        Get Oder By Id
    </a>
</div>

inveroryManagerApp/Views/Home/Products.cshtml
@{
    ViewData["Title"] = "Products Operations";
}
<div class="text-center">
    <h1 style="font-size: 4vw;">@ViewData["Title"]</h1>
</div>

<div class="position-absolute top-50 start-50 translate-middle ">
    <a asp-action="Index" asp-controller="home" class="btn btn-primary btn-lg"
    style="height: max-content width: max-content; font-size: 2vw;">
        List Items
    </a>
    <a asp-action="Index" asp-controller="home" class="btn btn-primary btn-lg" 
    style="height: max-content; width: max-content; font-size: 2vw;">
        Item Sold
    </a>
    <a asp-action="Index" asp-controller="home" class="btn btn-primary btn-lg" 
    style="height: max-content; width: max-content; font-size: 2vw;">
        Recall Item
    </a>
    <a asp-action="Index" asp-controller="home" class="btn btn-primary btn-lg" 
    style="height: max-content; width: max-content; font-size: 2vw;">
        Order Recieved
    </a>
</div>

inveroryManagerApp/Views/Home/Staffs.cshtml
@{
    ViewData["Title"] = "Staff Operations";
}
<div class="text-center">
    <h1 style="font-size: 4vw;">@ViewData["Title"]</h1>
</div>

<div class="position-absolute top-50 start-50 translate-middle ">
    <a asp-action="ListStaffs" asp-controller="Staff" class="btn btn-primary btn-lg"
       style="height: max-content">
        List Staffs
    </a>
    <a asp-action="AddStaff" asp-controller="Staff" class="btn btn-primary btn-lg"
       style="height: max-content">
        Add Staff
    </a>
</div>