inveroryManagerApp/Controllers/ItemsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using inveroryManagerApp.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace inveroryManagerApp.Controllers;

public partial class ItemsController : Controller
{

    public IActionResult ListItems()
    {
        DatabaseConnection db = new DatabaseConnection();
        List<ItemModel> listOfItems = db.GetListOfItems();
        ViewBag.Categories = db.GetItemCategoryModels(); 
        ViewBag.model = listOfItems;
        return View();
    }

    public delegate List<ItemModel> FilterDelegate(List<ItemModel> im);

    [HttpPost]
    public IActionResult ListItems(string filters)
    {
        DatabaseConnection db = new DatabaseConnection();
        FilterClass filterClass = new FilterClass();
        List<ItemModel> listOfItems = db.GetListOfItems();
        ViewBag.Categories = db.GetItemCategoryModels();

        if(filters == "Price: High to Low")
        {
            ViewBag.model = filterClass.PerformFilter(listOfItems, filterClass.PriceHighLow);
        }
        else if (filters == "Price: Low to High")
        {
            ViewBag.model = filterClass.PerformFilter(listOfItems, filterClass.PriceLowHigh);
        }
        else
        {
            ViewBag.model = listOfItems;
        }

        return View();
    }

    public class FilterClass
    {
        public FilterClass() { }

        public List<ItemModel> PerformFilter(List<ItemModel> items, FilterDelegate filter)
        {
            return filter.Invoke(items);
        }

        public List<ItemModel> PriceHighLow(List<ItemModel> list)
        {
            return list.OrderByDescending(x => x.SellPrice).ToList();
        }

        public List<ItemModel> PriceLowHigh(List<ItemModel> list)
        {
            return list.OrderBy(x => x.SellPrice).ToList();
        }
    }

    [HttpGet]
    public IActionResult AddCompany()
    {
        return View();
    }

    [HttpPost]
    public IActionResult AddCompany(CompanyModel company)
    {
        DatabaseConnection db = new DatabaseConnection();
        db.AddCompany(company);
        return Redirect("AddItem");
    }

    [HttpGet]
    public IActionResult AddSupplier()
    {
        return View();
    }

    [HttpPost]
    public IActionResult AddSupplier(SupplierModel supplier)
    {
        DatabaseConnection db = new DatabaseConnection();
        db.AddSupplier(supplier);
        return Redirect("AddItem");
    }

    [HttpGet]
    public IActionResult AddItemCategory()
    {
        return View();
    }

    [HttpPost]
    public IActionResult AddItemCategory(ItemCategoryModel itemCategory)
    {
        DatabaseConnection db = new DatabaseConnection();
        db.AddItemCategory(itemCategory);
        return Redirect("AddItem");
    }

    [HttpGet]
    public IActionResult AddItem()
    {
        DatabaseConnection db = new DatabaseConnection();

        List<CompanyModel> companyList = db.GetListOfCompany();
        List<SelectListItem> companyItems = new List<SelectListItem>();
        companyItems.Add(new SelectListItem { Text = "--Select Company--", Value = "0" });
        foreach (CompanyModel companyItem in companyList)
        {
            companyItems.Add(new SelectListItem { Text = companyItem.CompanyName, Value = companyItem.CompanyId.ToString() });
        }
        ViewBag.listCompany = companyItems;

        List<SupplierModel> supplierList = db.GetListOfSupplier();
        List<SelectListItem> supplierItems = new List<SelectListItem>();
        supplierItems.Add(new SelectListItem { Text = "--Select Supplier--", Value = "0" });
        foreach (SupplierModel supplierItem in supplierList)
        {
            supplierItems.Add(new SelectListItem { Text = supplierItem.SupplierName, Value = supplierItem.SupplierId.ToString() });
        }
        ViewBag.listSupplier = supplierItems;

        List<ItemCategoryModel> itemCategoryList = db.GetItemCategoryModels();
        List<SelectListItem> itemCategoryItems = new List<SelectListItem>();
        itemCategoryItems.Add(new SelectListItem { Text = "--Select Item Category--", Value = "0" });
        foreach (ItemCategoryModel itemCategoryItem in itemCategoryList)
        {
            itemCategoryItems.Add(new SelectListItem { Text = itemCategoryItem.ItemCategoryName, Value = itemCategoryItem.ItemCategoryId.ToString() });
        }
        ViewBag.listItemCategory = itemCategoryItems;
        return View();
    }

    [HttpPost]
    public IActionResult AddItem(ItemModel item)
    {
        DatabaseConnection db = new DatabaseConnection();
        db.AddItem(item);
        return Redirect("ListItems");
    }

    [HttpGet]
    public IActionResult ViewItem(int itemid)
    {
        DatabaseConnection db = new DatabaseConnection();
        ViewBag.model = db.GetItemByItemId(itemid);
        return View();
    }

}

inveroryManagerApp/Controllers/OrderController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using inveroryManagerApp.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using inveroryManagerApp.Event;

namespace inveroryManagerApp.Controllers;

public partial class OrdersController : Controller
{
    private readonly OrderProcessor _orderProcessor;
    public OrdersController()
  {
        _orderProcessor = new OrderProcessor();
        var emailService = new EmailService();
        _orderProcessor.OrderProcessed += emailService.OnOrderProcessed;
    }

    public IActionResult ListOrders()
    {
        DatabaseConnection db = new DatabaseConnection();
        List<OrderModel> listOfOrders = db.GetOrders();
        ViewBag.model = listOfOrders;
        return View();
    }

    [HttpGet]
    public IActionResult AddOrder()
    {
        DatabaseConnection db = new DatabaseConnection();
        List<ItemModel> itemList = db.GetListOfItems();
        List<SelectListItem> itemItems = new List<SelectListItem>();
        itemItems.Add(new SelectListItem { Text = "--Select Item--", Value = "0" });
        foreach (ItemModel itemItem in itemList)
        {
            itemItems.Add(new SelectListItem { Text = itemItem.ItemName, Value = itemItem.ItemId.ToString() });
        }
        ViewBag.listItem = itemItems;
        return View();
    }

    [HttpPost]
    public IActionResult AddOrder(OrderModel order)
    {
        DatabaseConnection db = new DatabaseConnection();
        db.AddOrder(order);
        _orderProcessor.ProcessOrder(order);
        return Redirect("ListOrders");
    }

    [HttpGet]
    public IActionResult OrderStatus()
    {
        return View();
    }

    [HttpPost]
    public IActionResult DisplayOrderStatus(OrderModel order)
    {
        DatabaseConnection db = new DatabaseConnection();
        order = db.GetOrderById(order.OrderId);
        ViewBag.model = order;
        if (order == null)
            return NoContent();
        return View();
    }
}

inveroryManagerApp/Views/Orders/AddOrder.cshtml
@model inveroryManagerApp.Models.OrderModel
@{
    ViewData["Title"] = "Add New Order";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .form-group{ margin: 5px; }
</style>

<div class="text-center">
    <h1 style="font-size: 4vw;">@ViewData["Title"]</h1>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group row">
            <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Item ID</label>
            <div class="col-sm-10">
                @Html.DropDownList("listItem", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.listItem, "", new { @class = "text-danger" })
                <a asp-action="AddItem" asp-controller="Items">
                    Add Item
                </a>
            </div>
        </div>

        <div class="form-group row">
            <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Quantity</label>
            <div class="col-sm-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Discount</label>
            <div class="col-sm-10">
                @Html.EditorFor(model => model.Discount, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                @Html.ValidationMessageFor(model => model.Discount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Price Paid</label>
            <div class="col-sm-10">
                @Html.EditorFor(model => model.PricePaid, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                @Html.ValidationMessageFor(model => model.PricePaid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </div>
}

inveroryManagerApp/Views/Orders/CheckOrderStatus.cshtml
<h1 style="font-size: 4vw;">@ViewData["name"]</h1>

inveroryManagerApp/Views/Orders/DisplayOrderStatus.cshtml
@{
    ViewData["Title"] = "Order Status";
}
<div class="text-center">
    <h1 style="font-size: 4vw;">@ViewData["Title"]</h1>
</div>

<div class="wrapper">
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Order ID</th>
                    <th scope="col">Item ID</th>
                    <th scope="col">Item Name</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Discount</th>
                    <th scope="col">Price Paid</th>
                </tr>
            </thead>
                <tbody>
                    <tr>
                        <td>@ViewBag.model.OrderId</td>
                        <td>@ViewBag.model.Item.ItemId</td>
                        <td>@ViewBag.model.Item.ItemName</td>
                        <td>@ViewBag.model.Quantity</td>
                        <td>@ViewBag.model.Discount</td>
                        <td>@ViewBag.model.PricePaid</td>
                    </tr>
                </tbody>
        </table>
    </div>
</div>

inveroryManagerApp/Views/Orders/ListOrders.cshtml
@{
    ViewData["Title"] = "List Orders";
}
<div class="text-center">
    <h1 style="font-size: 4vw;">@ViewData["Title"]</h1>
</div>

<div class="wrapper">
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Order ID</th>
                    <th scope="col">Item ID</th>
                    <th scope="col">Item Name</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Discount</th>
                    <th scope="col">Price Paid</th>
                </tr>
            </thead>
            @foreach (var order in ViewBag.model)
            {
                <tbody>
                    <tr>
                        <td>@order.OrderId</td>
                        <td>@order.Item.ItemId</td>
                        <td>@order.Item.ItemName</td>
                        <td>@order.Quantity</td>
                        <td>@order.Discount</td>
                        <td>@order.PricePaid</td>
                    </tr>
                </tbody>
            }
        </table>
    </div>
</div>

inveroryManagerApp/Views/Orders/OrderStatus.cshtml
@model inveroryManagerApp.Models.OrderModel
@{
    ViewData["Title"] = "Check Order Status";
}
<div class="text-center">
    <h1 style="font-size: 4vw;">@ViewData["Title"]</h1>
    <p1 style="font-size: 1vw;">Please Enter Order ID</p1>
</div>

@using (Html.BeginForm("DisplayOrderStatus", "Orders", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group row">
            <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Order ID</label>
            <div class="col-sm-10">
                @Html.EditorFor(model => model.OrderId, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                @Html.ValidationMessageFor(model => model.OrderId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </div>
}